### ISSUE TITLE
Date Required

### ISSUE THREAD

**Issue by JamesMTucker** [eba-diary/tagged-volumes#34]
Hi Sarah,

I was processing volume 17 today, to make some network files. I decided to write a check in my code, as I wanted to ensure the date for each entry was recorded for each entry. I noticed this entry is dated, but the meta data was overlooked. You might want to push an update to correct this. I've corrected it in the development version for now.

https://github.com/eba-diary/tagged-volumes/blob/908d6ca6ed2f0aa9a4cf87cd387ceaaaf276e0e5/diary-volumes/volume17.xml#L217

**Comment by ketchley** [comment]
Thanks James! Will dig into the date issue later this afternoon.

Dr. Sarah Ketchley / Egyptology | Digital Humanities (she/her/hers)
***@***.***
University of Washington
Department of Near Eastern Languages & Civilization
M220D Denny Hall
www.emmabandrews.org
www.sarahketchley.com
www.newbookdigitaltexts.org
